apiVersion: cnat.programming-kubernetes.info/v1alpha1
kind: At
metadata:
  labels:
    app.kubernetes.io/name: cnat-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: at-sample
spec:
  # TODO(user): Add fields here
